@extends('admin.layouts.app')

@section('title', isset($project) ? 'Edit Project' : 'Tambah Project')

@section('content')
@php
    $technologiesValue = '';
    if (isset($project) && $project->technologies) {
        $technologiesValue = is_array($project->technologies) 
            ? implode(', ', $project->technologies) 
            : $project->technologies;
    }
    $fields = [
        [
            'name' => 'title',
            'label' => 'Title',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Nama project',
        ],
        [
            'name' => 'slug',
            'label' => 'Slug',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'url-friendly-slug',
            'help' => 'Akan otomatis dibuat dari title jika dikosongkan',
        ],
        [
            'name' => 'short_description',
            'label' => 'Short Description',
            'type' => 'textarea',
            'rows' => 2,
            'placeholder' => 'Deskripsi singkat (untuk card)',
        ],
        [
            'name' => 'description',
            'label' => 'Full Description',
            'type' => 'textarea',
            'rows' => 5,
            'required' => true,
            'placeholder' => 'Deskripsi lengkap project',
        ],
        [
            'name' => 'category',
            'label' => 'Category',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Web Development, Mobile App, etc.',
        ],
        [
            'name' => 'technologies',
            'label' => 'Technologies (comma separated)',
            'type' => 'text',
            'default' => $technologiesValue,
            'placeholder' => 'Laravel, Vue.js, MySQL',
            'help' => 'Pisahkan dengan koma',
        ],
        [
            'name' => 'client_name',
            'label' => 'Client Name',
            'type' => 'text',
            'placeholder' => 'Nama klien (opsional)',
        ],
        [
            'name' => 'project_date',
            'label' => 'Project Date',
            'type' => 'date',
        ],
        [
            'name' => 'url',
            'label' => 'Live URL',
            'type' => 'url',
            'placeholder' => 'https://example.com',
        ],
        [
            'name' => 'github_url',
            'label' => 'GitHub URL',
            'type' => 'url',
            'placeholder' => 'https://github.com/username/project',
        ],
        [
            'name' => 'demo_url',
            'label' => 'Demo URL',
            'type' => 'url',
            'placeholder' => 'https://demo.example.com',
        ],
        [
            'name' => 'image',
            'label' => 'Featured Image',
            'type' => 'file',
            'accept' => 'image/*',
        ],
        [
            'name' => 'challenges',
            'label' => 'Challenges',
            'type' => 'textarea',
            'rows' => 3,
            'placeholder' => 'Tantangan yang dihadapi dalam project ini',
        ],
        [
            'name' => 'solution',
            'label' => 'Solution',
            'type' => 'textarea',
            'rows' => 3,
            'placeholder' => 'Solusi yang diterapkan',
        ],
        [
            'name' => 'order',
            'label' => 'Order',
            'type' => 'number',
            'default' => 0,
        ],
        [
            'name' => 'is_featured',
            'label' => 'Featured Project',
            'type' => 'checkbox',
            'checkbox_label' => 'Tampilkan sebagai featured project',
        ],
        [
            'name' => 'is_active',
            'label' => 'Active',
            'type' => 'checkbox',
            'checkbox_label' => 'Project aktif (ditampilkan di frontend)',
        ],
    ];
@endphp

@include('admin.components.form', [
    'action' => isset($project) ? route('admin.projects.update', $project) : route('admin.projects.store'),
    'method' => isset($project) ? 'PUT' : 'POST',
    'model' => $project ?? null,
    'fields' => $fields,
    'title' => isset($project) ? 'Edit Project' : 'Tambah Project',
    'cancelUrl' => route('admin.projects.index'),
    'gridCols' => 2,
])

<script>
document.getElementById('title').addEventListener('input', function() {
    const slugInput = document.getElementById('slug');
    if (!slugInput.value || slugInput.dataset.autoGenerated) {
        slugInput.value = this.value
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/(^-|-$)/g, '');
        slugInput.dataset.autoGenerated = 'true';
    }
});

document.getElementById('slug').addEventListener('input', function() {
    this.dataset.autoGenerated = 'false';
});
</script>
@endsection
